version: '3.7'

services:
  tpd_web:
    build: .
    container_name: tpd_web
    restart: always
    volumes:
      - ./:/app
    ports:
      - "127.0.0.1:7285:8000"
    env_file:
      - .env
    links:
      - mysql:db
      - redis:redis
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf

  redis:
    image: redis:6.2.10
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
