version: '3'

services:
  app:
    build: .
    container_name: serp_web
    restart: always
    volumes:
      - ./:/app
    ports:
      - "127.0.0.1:7285:8000"
    env_file:
      - .env
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: tpd
      MYSQL_USER: tpd_user
      MYSQL_PASSWORD: c$sk0dSdwQOgpf$p*r3Zf392
      MYSQL_ROOT_PASSWORD: c$sk0dSdwQOgpf$p*r3Zf392
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.2.10
    ports:
      - "6379:6379"

volumes:
  db_data: