"""create initial tables

Revision ID: 5cc738ba6efd
Revises: 
Create Date: 2023-07-07 03:48:39.130234

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5cc738ba6efd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'symbols',
        sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True, primary_key=True),
        sa.Column('symbol', sa.String(length=32), nullable=False, unique=True),
        sa.Column('url', sa.String(length=128), nullable=False, unique=True),
        sa.Column('technical_uuid', sa.String(length=32), nullable=True, unique=True),
        sa.Column('company_name', sa.String(length=128), nullable=False, unique=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'symbol_histories',
        sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True, primary_key=True),
        sa.Column('symbol_id', sa.BigInteger(), nullable=False),
        sa.Column('h_year', sa.Integer(), nullable=False),
        sa.Column('h_month', sa.Integer(), nullable=False),
        sa.Column('upper_band', sa.Double(), nullable=False),
        sa.Column('lower_band', sa.Double(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symbols')
    op.drop_table('symbol_histories')
    # ### end Alembic commands ###
